# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LivePlay' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LivePlay

pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage', '~> 3.8.1'
pod 'Masonry', '~> 1.0.1’
pod 'YYKit', '~> 1.0.9'
pod 'MJExtension'
pod 'LFLiveKit'


end
